export const GOOGLE_MAP_STYLE = [
  { elementType: 'geometry', stylers: [{ color: '#FAFAF9' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#71717A' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#FAFAF9' }] },
  { featureType: 'administrative.country', elementType: 'geometry.stroke', stylers: [{ color: '#D4D4D8' }] },
  { featureType: 'administrative.land_parcel', stylers: [{ visibility: 'off' }] },
  { featureType: 'administrative.neighborhood', stylers: [{ visibility: 'off' }] },
  { featureType: 'landscape', elementType: 'geometry', stylers: [{ color: '#FAFAF9' }] },
  { featureType: 'poi', elementType: 'labels', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#ECFDF5' }] },
  { featureType: 'poi.park', elementType: 'labels.text.fill', stylers: [{ color: '#16A34A' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#FFFFFF' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#E4E4E7' }] },
  { featureType: 'road.arterial', elementType: 'labels.text.fill', stylers: [{ color: '#A1A1AA' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#FFFFFF' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#71717A' }] },
  { featureType: 'road.local', elementType: 'labels', stylers: [{ visibility: 'simplified' }] },
  { featureType: 'transit', stylers: [{ visibility: 'off' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#E0F2FE' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#0EA5E9' }] },
];
